# Generated by Django 4.2.7 on 2023-12-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subcategory',
            field=models.ManyToManyField(to='book.subcategory'),
        ),
    ]
